# Generated by Django 4.2.11 on 2024-05-04 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('Taksi', 'Taksi'), ('Oziq-ovqat', 'Oziq-ovqat'), ('Texnika', 'Texnika'), ('O`tkazmalar', 'O`tkazmalar'), ('Kiyim', 'Kiyim'), ('Transport', 'Transport'), ('Komunal-To`lovlar', 'Komunal-To`lovlar'), ('Internet-Xizmatlari', 'Internet-Xizmatlari'), ('Telefoniya', 'Telefoniya'), ('Ta`lim', 'Ta`lim'), ('Jarimalar', 'Jarimalar'), ('Madaniy-Hordiq', 'Madaniy-Hordiq'), ('Xayriya-Fondlari', 'Xayriya-Fondlari'), ('Dorixona', 'Dorixona'), ('Boshqalar', 'Boshqalar'), ('Soliqlar', 'Soliqlar'), ('Notarius', 'Notarius'), ('Kredit', 'Kredit')], max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('money', models.IntegerField(default=0)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymeusers.paymeuser')),
            ],
        ),
        migrations.CreateModel(
            name='BaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('uz_card', 'UzCard'), ('humo_card', 'HumoCard'), ('visa_classic', 'Visa Classic'), ('visa_gold', 'Visa Gold')], max_length=50)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('pin_code', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField(default=datetime.datetime(2028, 5, 3, 10, 50, 6, 787228, tzinfo=datetime.timezone.utc), editable=False)),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymeusers.paymeuser')),
            ],
        ),
    ]
