# Generated by Django 4.2.11 on 2024-05-04 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymeusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 5, 3, 11, 9, 1, 178467, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
