# Generated by Django 4.2.11 on 2024-05-07 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymeusers', '0002_alter_basecard_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 5, 6, 11, 31, 6, 551367, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
