# Generated by Django 5.0.6 on 2024-05-14 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymeusers', '0003_alter_basecard_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 5, 13, 10, 18, 27, 168696, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
