# Generated by Django 4.2.11 on 2024-04-20 11:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymeusers', '0005_alter_humocard_expired_alter_humocard_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humocard',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 4, 19, 11, 4, 17, 621491, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='uzcard',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 4, 19, 11, 4, 17, 621491, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='visaclassic',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 4, 19, 11, 4, 17, 621491, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='visagold',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 4, 19, 11, 4, 17, 621491, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('Taksi', 'Taksi'), ('Oziq-ovqat', 'Oziq-ovqat'), ('Texnika', 'Texnika'), ('O`tkazmalar', 'O`tkazmalar'), ('Kiyim', 'Kiyim'), ('Transport', 'Transport'), ('Komunal-To`lovlar', 'Komunal-To`lovlar'), ('Internet-Xizmatlari', 'Internet-Xizmatlari'), ('Telefoniya', 'Telefoniya'), ('Ta`lim', 'Ta`lim'), ('Jarimalar', 'Jarimalar'), ('Madaniy-Hordiq', 'Madaniy-Hordiq'), ('Xayriya-Fondlari', 'Xayriya-Fondlari'), ('Dorixona', 'Dorixona'), ('Boshqalar', 'Boshqalar'), ('Soliqlar', 'Soliqlar'), ('Notarius', 'Notarius'), ('Kredit', 'Kredit')], max_length=40)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
