# Generated by Django 4.2.11 on 2024-04-25 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymeusers', '0007_paymenthistory_money_alter_humocard_expired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='humocard',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 4, 24, 10, 34, 5, 35075, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='uzcard',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 4, 24, 10, 34, 5, 35075, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='visaclassic',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 4, 24, 10, 34, 5, 35075, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='visagold',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 4, 24, 10, 34, 5, 35075, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='humocard',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymeusers.paymeuser'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymeusers.paymeuser'),
        ),
        migrations.AlterField(
            model_name='uzcard',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymeusers.paymeuser'),
        ),
        migrations.AlterField(
            model_name='visaclassic',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymeusers.paymeuser'),
        ),
        migrations.AlterField(
            model_name='visagold',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymeusers.paymeuser'),
        ),
    ]
