# Generated by Django 5.0.6 on 2024-05-25 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymeusers', '0007_transactions_alter_basecard_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2028, 5, 24, 10, 14, 27, 825879, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
